### ISSUE TITLE
Error-handling

### ISSUE THREAD

**Issue by oliverjam** [fac19/week6-CADO#43]
Make sure you always catch errors and send a response to the browser. Your `signupPostHandler` doesn't do this, which is why the Heroku app crashes when I submit the sign up form.

**Comment by akomiqaia** [comment]
I can sign up on heroku. How does it crash? in my case the form gets submitted and then i am getting redirected to the home page and remain signed in.

**Comment by oliverjam** [comment]
🤷 I just got the Heroku app error instead of being redirected after I submitted
